# This is a configuration example for the node labeller which includes
# ClusterRole and ClusterRoleBinding definitions, as well as the
# DeamonSet configuration that deploys the actual node labeller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: radeon-labeller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: radeon-labeller-role
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - radeon-labeller-role
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - watch
  - get
  - list
  - update
  resourceNames:
  - radeon-labeller-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: radeon-labeller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: radeon-labeller-role
subjects:
- kind: ServiceAccount
  name: radeon-labeller-role
  namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: amdgpu-labeller-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: amdgpu-lr-ds
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: amdgpu-lr-ds
    spec:
      serviceAccount: radeon
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - image: rocm/k8s-device-plugin:labeller-latest
        name: amdgpu-lr-cntr
        imagePullPolicy: Always
        workingDir: /root
        command: ["./k8s-node-labeller"]
        args: ["-vram", "-cu-count", "-simd-count", "-device-id", "-family"]
        env:
          - name: DS_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          privileged: true #Needed for /dev
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: sys
            mountPath: /sys
          - name: dev
            mountPath: /dev
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: dev
          hostPath:
            path: /dev
