---
{{- if .Values.labeller.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-{{ .Chart.Name }}-node-labeller
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["watch", "get", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-{{ .Chart.Name }}-labeller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-{{ .Chart.Name }}-node-labeller
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-node-labeller-sa
  namespace: {{ .Release.Namespace }}
{{- end }}