---
{{- if .Values.labeller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-node-labeller-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "amd-gpu.labels" . | nindent 4 }}
  {{- with .Values.lbl.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
