name: CI - Build Images

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: device-plugin
            target: build-device-plugin
          - name: labeller
            target: build-labeller
          - name: ubi-device-plugin
            target: build-ubi-device-plugin
          - name: ubi-labeller
            target: build-ubi-labeller
    name: build (${{ matrix.name }})
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Build ${{ matrix.name }}
        run: make ${{ matrix.target }}
